version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVICE_PORT}:5000
    depends_on:
      - db

  db:
    image: mariadb:10.4.15
    restart: always
    ports:
      - ${DATABASE_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}